# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 322b13558ccea406705a452eafc1de261b1727832752326ffdfb17efef13fec5ea5c807d59187d952570c65da08d69effbdc655a0e75d2218736f611e69599ce

test:
  secret_key_base: 65695e7b0faaa155d2387d79fd75298cbcd7be3965b84ce52c051341b7c88aff64b65d1d14aedcdfb9ec8bea7a6f756102b88cd00f7ae31970583a06dedde27b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
